# Site settings
title: Ross Dakin
email: rossdakin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tales of amaranthine wanderlust.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rossdak.in" # the base hostname & protocol for your site
twitter_username: rossdakin
github_username:  rossdakin

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman